server:
  port: 8088
spring:
  application:
    name: oozieweb
  freemarker:
    template-loader-path: classpath:/templates/
    catche: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .html